---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Update and install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key (dearmored) to keyring
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
          | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set permissions on Docker GPG keyring
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: file
        mode: '0644'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ {'x86_64':'amd64','aarch64':'arm64','armv7l':'armhf','armv6l':'armhf'}.get(ansible_architecture, ansible_architecture) }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Configure Docker log rotation
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "50m",
              "max-file": "3"
            }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Find existing Docker log files
      ansible.builtin.find:
        paths: /var/lib/docker/containers
        patterns:
          - "*-json.log"
        file_type: file
        recurse: yes
      register: docker_logs
      failed_when: false

    - name: Truncate Docker container logs
      ansible.builtin.command: "truncate -s 0 {{ item.path }}"
      loop: "{{ docker_logs.files | default([]) }}"
      when: (docker_logs.files | default([])) | length > 0
      loop_control:
        label: "{{ item.path }}"
        
    - name: Restart Docker to apply log config
      systemd:
        name: docker
        state: restarted
        enabled: yes