#SHADOWROCKET

# Shadowrocket configuration
# Generated by CFG App

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = https://1.1.1.1/dns-query, https://8.8.8.8/dns-query
fallback-dns-server = https://dns.google/dns-query, https://cloudflare-dns.com/dns-query
ipv6 = false

[Rule]
# VPN check
DOMAIN-SUFFIX,whatismyipaddress.com,PROXY

# RULE-SET entries will be expanded here
RULE-SET,https://s.dimonb.com/lists/rutracker.list,PROXY
RULE-SET,https://s.dimonb.com/lists/binance.list,PROXY
RULE-SET,https://s.dimonb.com/lists/zoom.list,PROXY
RULE-SET,https://s.dimonb.com/lists/google.list,PROXY
RULE-SET,https://s.dimonb.com/lists/meta.list,PROXY
RULE-SET,https://s.dimonb.com/lists/telegram.list,PROXY
RULE-SET,https://s.dimonb.com/lists/twitter.list,PROXY
RULE-SET,https://s.dimonb.com/lists/tiktok.list,PROXY
RULE-SET,https://s.dimonb.com/lists/whatsapp.list,PROXY
RULE-SET,https://s.dimonb.com/lists/chatgpt.list,PROXY
RULE-SET,https://s.dimonb.com/lists/apple-private.list,PROXY

# Default rule
FINAL,DIRECT

[Host]
localhost = 127.0.0.1


